# Project Name
TARGET = wavae_daisy

# Sources
CPP_SOURCES = wavae_daisy.cpp

# Library Locations
LIBDAISY_DIR = ../libDaisy/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
